### ISSUE TITLE
how to set indent color?

### ISSUE THREAD

**Issue by ticmaisdev** [exyte/AndroidAnimatedNavigationBar#1]
I've got a gradient background, which means I need a transparent indent color.

Can you guys help me out with that?

**Comment by AlexYudenkov** [comment]
Hello! Although you have closed the issue, I have decided to respond to you. From my understanding, you need a gradient for the background. Currently, you can only specify the color. However, I think we can add the option to use a `Brush`, allowing you to utilize gradients.

**Comment by ticmaisdev** [comment]
Actually, that was a problem at my end. The package does apply transparent indent, it's jut I had a white box behind that wasn't aware of. I'm newbie in compose. I'm sorry for the trouble.

But would like to still keep the other issue as feature request. It would be great to have a cutout bottombar with an action button right in the middle by default.
