### ISSUE TITLE
would it be possible to create an indented action button right in the middle of the navigation bar?

### ISSUE THREAD

**Issue by ticmaisdev** [exyte/AndroidAnimatedNavigationBar#2]
I've got 3 buttons: home, action button, stats.

The action button is not a navigation button, but it fits good in the middle of the navigation bar. I've managed to make the animated ball jump over the this middle button, which looks cool but the design would perfect if this action button had a transparent indent.

as you can see (I hope so at least), there's an indented curve under action button.

![Untitled](https://github.com/exyte/AndroidAnimatedNavigationBar/assets/128381407/49163b81-2847-4fbf-abf2-fbb18993f1d0)

**Comment by AlexYudenkov** [comment]
Hello! It seems that your design is too specific, and we can't add it to the library. However, I have created a quick example that demonstrates how you can achieve the desired indentation by making slight modifications to our navigation bar code. You can manipulate the shape of the desired indent to get it just the way you want it. 
[code](https://github.com/exyte/AndroidAnimatedNavigationBar/compare/master...indent_action_button)
![centralIndent](https://github.com/exyte/AndroidAnimatedNavigationBar/assets/57913130/3caa17b5-0ffd-4bd3-b6dc-d1c34075ed8b)

**Comment by ticmaisdev** [comment]
you're awesome. thank you so much
